#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --time=7-00:00:00 # time allocation, which has the format (D-HH:MM:SS), here set to 1 hour
#SBATCH --mem=128GB # specify the memory required per node (here set to 4 GB)
#SBATCH --account=OD-228206
# # # don't want gpu SBATCH --gres=gpu:1 # generic resource required (here requires 4 GPUs)
#SBATCH --mail-type=END # Send a notification email when the job is done (=END)
#SBATCH --mail-type=FAIL # Send a notification email when the job fails (=FAIL)
#SBATCH --mail-user=diksha.goel@data61.csiro.au

module load cuda/11.2.1
module load netcdf/4.8.0
module load fftw/3.3.9

conda activate NetShare
python3 driver.py
conda deactivate

